-- 成本库 MVP 建表 SQL
-- 状态：初稿
-- 说明：只放表结构，不放测试数据。
-- 数据库：costree_mvp

CREATE DATABASE IF NOT EXISTS `costree_mvp`
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE `costree_mvp`;

CREATE TABLE IF NOT EXISTS `cost_source_project_tree` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `source_project_id` varchar(64) NOT NULL COMMENT '源项目主键ID，业务参考字段xmnm',
  `project_code` varchar(64) NOT NULL COMMENT '主业项目编号',
  `project_name` varchar(200) NOT NULL COMMENT '主业项目名称',
  `project_category` varchar(128) DEFAULT NULL COMMENT '主业项目所属类别',
  `domain_code` varchar(64) DEFAULT NULL COMMENT '所属领域编码',
  `domain_name` varchar(128) DEFAULT NULL COMMENT '所属领域名称',
  `parent_source_id` varchar(64) DEFAULT NULL COMMENT '上级节点ID',
  `parent_path` varchar(1000) DEFAULT NULL COMMENT '父路径',
  `level_no` int DEFAULT NULL COMMENT '级数，业务参考字段JS',
  `source_lastmodify` datetime DEFAULT NULL COMMENT '源系统最后修改时间',
  `custom_01` varchar(255) DEFAULT NULL COMMENT '自定义1',
  `custom_02` varchar(255) DEFAULT NULL COMMENT '自定义2',
  `custom_03` varchar(255) DEFAULT NULL COMMENT '自定义3',
  `custom_04` varchar(255) DEFAULT NULL COMMENT '自定义4',
  `custom_05` varchar(255) DEFAULT NULL COMMENT '自定义5',
  `custom_06` varchar(255) DEFAULT NULL COMMENT '自定义6',
  `custom_07` varchar(255) DEFAULT NULL COMMENT '自定义7',
  `custom_08` varchar(255) DEFAULT NULL COMMENT '自定义8',
  `custom_09` varchar(255) DEFAULT NULL COMMENT '自定义9',
  `custom_10` varchar(255) DEFAULT NULL COMMENT '自定义10',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cost_source_project_tree_source` (`tenant_id`, `source_project_id`),
  KEY `idx_cost_source_project_tree_code` (`tenant_id`, `project_code`),
  KEY `idx_cost_source_project_tree_parent` (`tenant_id`, `parent_source_id`),
  KEY `idx_cost_source_project_tree_domain` (`tenant_id`, `domain_code`),
  KEY `idx_cost_source_project_tree_lastmodify` (`tenant_id`, `source_lastmodify`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='成本库-源主业项目树';

CREATE TABLE IF NOT EXISTS `cost_model_node` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `parent_id` bigint NOT NULL DEFAULT 0 COMMENT '父节点编号',
  `node_code` varchar(64) NOT NULL COMMENT '节点编码',
  `node_name` varchar(128) NOT NULL COMMENT '节点名称',
  `node_type` varchar(32) NOT NULL COMMENT '节点类型：DOMAIN/SERIES/MODEL',
  `domain_code` varchar(64) DEFAULT NULL COMMENT '所属领域编码',
  `sort` int NOT NULL DEFAULT 0 COMMENT '排序',
  `status` varchar(32) NOT NULL DEFAULT 'ENABLE' COMMENT '状态：ENABLE/DISABLE',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cost_model_node_code` (`tenant_id`, `node_code`),
  KEY `idx_cost_model_node_parent` (`tenant_id`, `parent_id`),
  KEY `idx_cost_model_node_type` (`tenant_id`, `node_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='成本库-领域系列型号树';

CREATE TABLE IF NOT EXISTS `cost_project` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `project_code` varchar(64) NOT NULL COMMENT '主业项目编号',
  `project_name` varchar(200) NOT NULL COMMENT '主业项目名称',
  `model_node_id` bigint DEFAULT NULL COMMENT '型号树节点编号',
  `domain_code` varchar(64) NOT NULL COMMENT '所属领域编码',
  `domain_name` varchar(128) NOT NULL COMMENT '所属领域名称',
  `category_code` varchar(64) DEFAULT NULL COMMENT '所属类别/系列编码',
  `category_name` varchar(128) DEFAULT NULL COMMENT '所属类别/系列名称',
  `model_code` varchar(64) DEFAULT NULL COMMENT '型号/项目编码',
  `model_name` varchar(128) DEFAULT NULL COMMENT '型号/项目名称',
  `batch_no` varchar(64) DEFAULT NULL COMMENT '批次',
  `stage_codes` varchar(128) DEFAULT NULL COMMENT '阶段集合，逗号分隔',
  `unit_id` bigint DEFAULT NULL COMMENT '单位编号',
  `unit_name` varchar(128) DEFAULT NULL COMMENT '单位名称',
  `unit_type` varchar(64) DEFAULT NULL COMMENT '单位属性',
  `project_office_status` varchar(32) NOT NULL DEFAULT 'NOT_FILLED' COMMENT '项目办填报状态：NOT_FILLED/PART_FILLED/FILLED',
  `unit_fill_status` varchar(32) NOT NULL DEFAULT 'NOT_FILLED' COMMENT '研制单位填报状态：NOT_FILLED/PART_FILLED/FILLED',
  `audit_status` varchar(32) NOT NULL DEFAULT 'DRAFT' COMMENT '审批/提交状态：DRAFT/SUBMITTED/APPROVED/REJECTED',
  `dept_id` bigint DEFAULT NULL COMMENT '数据权限部门编号【需确认】',
  `owner_user_id` bigint DEFAULT NULL COMMENT '项目负责人用户编号【需确认】',
  `warning_status` varchar(32) NOT NULL DEFAULT 'NORMAL' COMMENT '预警状态：NORMAL/OVER',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cost_project_code` (`tenant_id`, `project_code`),
  KEY `idx_cost_project_domain` (`tenant_id`, `domain_code`),
  KEY `idx_cost_project_model` (`tenant_id`, `model_node_id`),
  KEY `idx_cost_project_status` (`tenant_id`, `audit_status`, `project_office_status`, `unit_fill_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='成本库-主业项目锚定';

CREATE TABLE IF NOT EXISTS `cost_unit_dict` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `accounting_unit_id` varchar(64) DEFAULT NULL COMMENT '核算单位ID',
  `accounting_unit_code` varchar(64) NOT NULL COMMENT '核算单位编号',
  `accounting_unit_name` varchar(128) NOT NULL COMMENT '核算单位名称',
  `manage_unit_code` varchar(64) DEFAULT NULL COMMENT '管理单位编号',
  `manage_unit_name` varchar(128) DEFAULT NULL COMMENT '管理单位名称',
  `contact_unit_code` varchar(64) DEFAULT NULL COMMENT '往来单位编号',
  `contact_unit_name` varchar(128) DEFAULT NULL COMMENT '往来单位名称',
  `inside_group` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否集团内',
  `inside_institute` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否八院内',
  `unit_id` bigint DEFAULT NULL COMMENT '中台单位ID【需确认映射来源】',
  `status` varchar(32) NOT NULL DEFAULT 'ENABLE' COMMENT '状态：ENABLE/DISABLE',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cost_unit_dict_code` (`tenant_id`, `accounting_unit_code`),
  KEY `idx_cost_unit_dict_name` (`tenant_id`, `accounting_unit_name`),
  KEY `idx_cost_unit_dict_inside` (`tenant_id`, `inside_institute`),
  KEY `idx_cost_unit_dict_status` (`tenant_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='成本库-单位字典';

CREATE TABLE IF NOT EXISTS `cost_project_basic` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `project_id` bigint NOT NULL COMMENT '主业项目编号',
  `project_code` varchar(64) NOT NULL COMMENT '主业项目编号冗余',
  `project_name` varchar(200) NOT NULL COMMENT '主业项目名称冗余',
  `subsystem_name` varchar(128) DEFAULT NULL COMMENT '分系统/产品配套',
  `user_name` varchar(128) DEFAULT NULL COMMENT '用户',
  `acquire_method` varchar(64) DEFAULT NULL COMMENT '项目获取方式',
  `batch_category` varchar(128) DEFAULT NULL COMMENT '批次/类别',
  `platform_series` varchar(128) DEFAULT NULL COMMENT '所属平台/系列',
  `research_unit_id` bigint DEFAULT NULL COMMENT '承研单位编号',
  `research_unit_name` varchar(128) DEFAULT NULL COMMENT '承研单位名称',
  `target_price` decimal(18,2) DEFAULT NULL COMMENT '投标/目标价格，单位万元',
  `competitor_unit_1` varchar(128) DEFAULT NULL COMMENT '对手单位1',
  `competitor_price_1` decimal(18,2) DEFAULT NULL COMMENT '对手竞标价格1，单位万元',
  `competitor_unit_2` varchar(128) DEFAULT NULL COMMENT '对手单位2',
  `competitor_price_2` decimal(18,2) DEFAULT NULL COMMENT '对手竞标价格2，单位万元',
  `contract_amount` decimal(18,2) DEFAULT NULL COMMENT '竞争项目合同金额，单位万元',
  `target_cost_amount` decimal(18,2) DEFAULT NULL COMMENT '型号项目目标成本，单位万元',
  `approved_amount` decimal(18,2) DEFAULT NULL COMMENT '审定金额，单位万元',
  `cycle_start` varchar(7) DEFAULT NULL COMMENT '研制周期起，格式YYYY-MM',
  `cycle_end` varchar(7) DEFAULT NULL COMMENT '研制周期止，格式YYYY-MM',
  `stage_code` varchar(32) DEFAULT NULL COMMENT '阶段',
  `basic_info` text COMMENT '基本情况',
  `status` varchar(32) NOT NULL DEFAULT 'DRAFT' COMMENT '记录状态：DRAFT/SUBMITTED/APPROVED/REJECTED',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `import_batch_id` bigint DEFAULT NULL COMMENT '导入批次编号',
  `dept_id` bigint DEFAULT NULL COMMENT '数据权限部门编号【需确认】',
  `owner_user_id` bigint DEFAULT NULL COMMENT '填报负责人用户编号【需确认】',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_cost_project_basic_project` (`tenant_id`, `project_id`),
  KEY `idx_cost_project_basic_stage` (`tenant_id`, `stage_code`),
  KEY `idx_cost_project_basic_status` (`tenant_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='成本库-项目基本情况';

CREATE TABLE IF NOT EXISTS `cost_work_order` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `project_id` bigint NOT NULL COMMENT '主业项目编号',
  `project_code` varchar(64) NOT NULL COMMENT '主业项目编号冗余',
  `project_name` varchar(200) NOT NULL COMMENT '主业项目名称冗余',
  `unit_id` bigint DEFAULT NULL COMMENT '单位编号',
  `unit_name` varchar(128) DEFAULT NULL COMMENT '单位名称',
  `work_order_no` varchar(64) NOT NULL COMMENT '工作令编号',
  `work_order_name` varchar(200) NOT NULL COMMENT '工作令名称',
  `product_target_cost` decimal(18,2) DEFAULT NULL COMMENT '研制产品目标成本，单位万元',
  `book_cost_amount` decimal(18,2) DEFAULT NULL COMMENT '账面成本，单位万元，外网测试用于预警',
  `stage_codes` varchar(128) DEFAULT NULL COMMENT '阶段集合，逗号分隔',
  `max_stage_code` varchar(32) DEFAULT NULL COMMENT '最高阶段',
  `subsystem_name` varchar(128) DEFAULT NULL COMMENT '所属分系统',
  `product_short_name` varchar(128) DEFAULT NULL COMMENT '产品简称',
  `quantity` int DEFAULT NULL COMMENT '配套数量',
  `vertical_division` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否属于纵向分工',
  `approved_amount` decimal(18,2) DEFAULT NULL COMMENT '审定金额，单位万元',
  `status` varchar(32) NOT NULL DEFAULT 'DRAFT' COMMENT '记录状态：DRAFT/SUBMITTED/APPROVED/REJECTED',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `import_batch_id` bigint DEFAULT NULL COMMENT '导入批次编号',
  `dept_id` bigint DEFAULT NULL COMMENT '数据权限部门编号【需确认】',
  `owner_user_id` bigint DEFAULT NULL COMMENT '填报负责人用户编号【需确认】',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cost_work_order_no` (`tenant_id`, `work_order_no`),
  KEY `idx_cost_work_order_project` (`tenant_id`, `project_id`),
  KEY `idx_cost_work_order_stage` (`tenant_id`, `max_stage_code`),
  KEY `idx_cost_work_order_status` (`tenant_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='成本库-工作令基础信息';

CREATE TABLE IF NOT EXISTS `cost_work_order_project_ref` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `source_work_order_id` varchar(64) NOT NULL COMMENT '源工作令ID',
  `accounting_unit_code` varchar(64) DEFAULT NULL COMMENT '核算单位编号',
  `accounting_unit_name` varchar(128) DEFAULT NULL COMMENT '核算单位名称',
  `fiscal_year` varchar(8) DEFAULT NULL COMMENT '年度',
  `work_order_no` varchar(64) NOT NULL COMMENT '工作令编号',
  `work_order_name` varchar(200) DEFAULT NULL COMMENT '工作令名称',
  `disabled` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否停用',
  `linked_project_code` varchar(64) DEFAULT NULL COMMENT '关联主业项目编号',
  `linked_project_name` varchar(200) DEFAULT NULL COMMENT '关联主业项目名称',
  `linked_source_project_id` varchar(64) DEFAULT NULL COMMENT '关联主业项目ID，源项目主键ID',
  `project_id` bigint DEFAULT NULL COMMENT '成本库项目主键，匹配后写入',
  `custom_01` varchar(255) DEFAULT NULL COMMENT '自定义1',
  `custom_02` varchar(255) DEFAULT NULL COMMENT '自定义2',
  `custom_03` varchar(255) DEFAULT NULL COMMENT '自定义3',
  `custom_04` varchar(255) DEFAULT NULL COMMENT '自定义4',
  `custom_05` varchar(255) DEFAULT NULL COMMENT '自定义5',
  `custom_06` varchar(255) DEFAULT NULL COMMENT '自定义6',
  `custom_07` varchar(255) DEFAULT NULL COMMENT '自定义7',
  `custom_08` varchar(255) DEFAULT NULL COMMENT '自定义8',
  `custom_09` varchar(255) DEFAULT NULL COMMENT '自定义9',
  `custom_10` varchar(255) DEFAULT NULL COMMENT '自定义10',
  `source_lastmodify` datetime DEFAULT NULL COMMENT '源系统最后修改时间【需确认来源字段】',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cost_work_order_project_ref_source` (`tenant_id`, `source_work_order_id`),
  KEY `idx_cost_work_order_project_ref_no` (`tenant_id`, `work_order_no`),
  KEY `idx_cost_work_order_project_ref_project` (`tenant_id`, `linked_project_code`),
  KEY `idx_cost_work_order_project_ref_unit` (`tenant_id`, `accounting_unit_code`, `fiscal_year`),
  KEY `idx_cost_work_order_project_ref_disabled` (`tenant_id`, `disabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='成本库-工作令关联主业项目字典';

CREATE TABLE IF NOT EXISTS `cost_work_order_ledger_detail` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `source_detail_id` varchar(64) NOT NULL COMMENT '源明细内码，业务参考字段ysnm',
  `fiscal_year` varchar(8) DEFAULT NULL COMMENT '会计年度，业务参考字段kjnd',
  `accounting_period` varchar(16) DEFAULT NULL COMMENT '会计期间，业务参考字段kjqj',
  `voucher_date` date DEFAULT NULL COMMENT '凭证日期，业务参考字段pzrq',
  `voucher_no` varchar(64) DEFAULT NULL COMMENT '凭证编号，业务参考字段pzbh',
  `accounting_unit_id` varchar(64) DEFAULT NULL COMMENT '单位主键，业务参考字段dwid',
  `accounting_unit_code` varchar(64) DEFAULT NULL COMMENT '单位编号，业务参考字段dwbh',
  `accounting_unit_name` varchar(128) DEFAULT NULL COMMENT '单位名称，业务参考字段dwmc',
  `manage_unit_name` varchar(128) DEFAULT NULL COMMENT '管理单位，业务参考字段gldw',
  `subject_id` varchar(64) DEFAULT NULL COMMENT '科目主键，业务参考字段kmid',
  `subject_code` varchar(64) DEFAULT NULL COMMENT '科目编号，业务参考字段kmbh',
  `subject_name` varchar(128) DEFAULT NULL COMMENT '科目名称，业务参考字段kmmc',
  `project_code` varchar(64) DEFAULT NULL COMMENT '项目编号，业务参考字段xmbh',
  `source_project_id` varchar(64) DEFAULT NULL COMMENT '项目主键，业务参考字段xmnm',
  `project_name` varchar(200) DEFAULT NULL COMMENT '项目名称，业务参考字段xmmc',
  `source_work_order_id` varchar(64) DEFAULT NULL COMMENT '工作令主键，业务参考字段gzlnm',
  `work_order_no` varchar(64) DEFAULT NULL COMMENT '工作令编号，业务参考字段gzllb',
  `work_order_name` varchar(200) DEFAULT NULL COMMENT '工作令名称，业务参考字段gzlmc',
  `debit_credit` varchar(16) DEFAULT NULL COMMENT '记账方向，业务参考字段jzfx',
  `amount` decimal(20,2) NOT NULL DEFAULT 0.00 COMMENT '金额，源系统单位【需确认，暂按元】',
  `amount_wan` decimal(18,2) DEFAULT NULL COMMENT '金额折算万元，用于成本库展示聚合【需确认换算口径】',
  `summary_text` varchar(500) DEFAULT NULL COMMENT '辅助摘要，业务参考字段yt',
  `source_lastmodify` datetime DEFAULT NULL COMMENT '源系统最后修改时间，业务参考字段lastmodify',
  `second_subject_code` varchar(64) DEFAULT NULL COMMENT '二级科目编号，业务参考字段ejkmbh',
  `second_subject_name` varchar(128) DEFAULT NULL COMMENT '二级科目名称，业务参考字段ejkmmc',
  `source_timestamp` varchar(64) DEFAULT NULL COMMENT '源时间戳，业务参考字段dwts',
  `resolved_stage_code` varchar(32) DEFAULT NULL COMMENT '成本库归集阶段，按工作令最高阶段解析后写入',
  `project_id` bigint DEFAULT NULL COMMENT '成本库项目主键，匹配后写入',
  `work_order_id` bigint DEFAULT NULL COMMENT '成本库工作令主键，匹配后写入',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cost_work_order_ledger_detail_source` (`tenant_id`, `source_detail_id`),
  KEY `idx_cost_work_order_ledger_detail_project` (`tenant_id`, `project_code`),
  KEY `idx_cost_work_order_ledger_detail_work_order` (`tenant_id`, `work_order_no`),
  KEY `idx_cost_work_order_ledger_detail_unit` (`tenant_id`, `accounting_unit_code`),
  KEY `idx_cost_work_order_ledger_detail_subject` (`tenant_id`, `subject_code`),
  KEY `idx_cost_work_order_ledger_detail_period` (`tenant_id`, `fiscal_year`, `accounting_period`),
  KEY `idx_cost_work_order_ledger_detail_lastmodify` (`tenant_id`, `source_lastmodify`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='成本库-工作令账面成本明细';

CREATE TABLE IF NOT EXISTS `cost_unit_cost_detail` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `project_id` bigint NOT NULL COMMENT '主业项目编号',
  `project_code` varchar(64) NOT NULL COMMENT '主业项目编号冗余',
  `project_name` varchar(200) NOT NULL COMMENT '主业项目名称冗余',
  `domain_code` varchar(64) NOT NULL COMMENT '所属领域编码',
  `domain_name` varchar(128) NOT NULL COMMENT '所属领域名称',
  `model_node_id` bigint DEFAULT NULL COMMENT '型号树节点编号',
  `model_code` varchar(64) DEFAULT NULL COMMENT '型号/项目编码',
  `model_name` varchar(128) DEFAULT NULL COMMENT '型号/项目名称',
  `unit_id` bigint DEFAULT NULL COMMENT '研制单位编号',
  `unit_name` varchar(128) NOT NULL COMMENT '研制单位名称',
  `stage_code` varchar(32) NOT NULL COMMENT '阶段',
  `contract_amount` decimal(18,2) DEFAULT NULL COMMENT '合同金额，单位万元',
  `income_amount` decimal(18,2) DEFAULT NULL COMMENT '到款/收入金额，单位万元',
  `target_cost_amount` decimal(18,2) DEFAULT NULL COMMENT '目标成本，单位万元',
  `book_cost_amount` decimal(18,2) DEFAULT NULL COMMENT '账面成本，单位万元',
  `salary_amount` decimal(18,2) DEFAULT NULL COMMENT '薪酬，单位万元',
  `material_amount` decimal(18,2) DEFAULT NULL COMMENT '材料费，单位万元',
  `outsource_amount` decimal(18,2) DEFAULT NULL COMMENT '外协费，单位万元',
  `manage_amount` decimal(18,2) DEFAULT NULL COMMENT '管理费，单位万元',
  `fuel_power_amount` decimal(18,2) DEFAULT NULL COMMENT '燃料动力，单位万元',
  `other_amount` decimal(18,2) DEFAULT NULL COMMENT '其他，单位万元',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cost_unit_cost_detail_unit_stage` (`tenant_id`, `project_code`, `stage_code`, `unit_name`),
  KEY `idx_cost_unit_cost_detail_domain` (`tenant_id`, `domain_code`),
  KEY `idx_cost_unit_cost_detail_unit` (`tenant_id`, `unit_name`),
  KEY `idx_cost_unit_cost_detail_model` (`tenant_id`, `model_node_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='成本库-研制单位成本结构明细';

CREATE TABLE IF NOT EXISTS `cost_import_batch` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `import_type` varchar(64) NOT NULL COMMENT '导入类型：PROJECT_BASIC/WORK_ORDER',
  `file_name` varchar(255) DEFAULT NULL COMMENT '原始文件名',
  `file_url` varchar(500) DEFAULT NULL COMMENT '文件地址',
  `total_count` int NOT NULL DEFAULT 0 COMMENT '总行数',
  `success_count` int NOT NULL DEFAULT 0 COMMENT '成功行数',
  `failure_count` int NOT NULL DEFAULT 0 COMMENT '失败行数',
  `update_support` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否支持覆盖更新',
  `status` varchar(32) NOT NULL DEFAULT 'SUCCESS' COMMENT '导入状态：SUCCESS/PART_SUCCESS/FAILED',
  `error_file_url` varchar(500) DEFAULT NULL COMMENT '错误文件地址',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_cost_import_batch_type` (`tenant_id`, `import_type`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='成本库-导入批次';

CREATE TABLE IF NOT EXISTS `cost_import_error` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `batch_id` bigint NOT NULL COMMENT '导入批次编号',
  `row_num` int NOT NULL COMMENT 'Excel行号',
  `field_name` varchar(128) DEFAULT NULL COMMENT '字段名',
  `error_message` varchar(500) NOT NULL COMMENT '错误原因',
  `raw_data` text COMMENT '原始行数据JSON',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_cost_import_error_batch` (`tenant_id`, `batch_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='成本库-导入错误明细';

CREATE TABLE IF NOT EXISTS `cost_warning_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `project_id` bigint NOT NULL COMMENT '主业项目编号',
  `work_order_id` bigint DEFAULT NULL COMMENT '工作令编号，可为空',
  `warning_source` varchar(64) NOT NULL DEFAULT 'WORK_ORDER' COMMENT '预警来源：PROJECT/WORK_ORDER',
  `warning_title` varchar(255) NOT NULL COMMENT '预警标题',
  `target_cost_amount` decimal(18,2) NOT NULL COMMENT '目标成本，单位万元',
  `actual_cost_amount` decimal(18,2) NOT NULL COMMENT '实际/账面成本，单位万元',
  `over_amount` decimal(18,2) NOT NULL COMMENT '超支金额，单位万元',
  `over_rate` decimal(8,4) NOT NULL COMMENT '超支比例，例如0.1250',
  `threshold_rate` decimal(8,4) NOT NULL DEFAULT 0.1000 COMMENT '阈值比例，外网测试默认10%',
  `warning_level` varchar(32) NOT NULL DEFAULT 'OVER' COMMENT '预警等级：NORMAL/OVER',
  `responsible_unit_name` varchar(128) DEFAULT NULL COMMENT '责任单位',
  `push_status` varchar(32) NOT NULL DEFAULT 'NOT_PUSHED' COMMENT '推送状态：NOT_PUSHED/PUSHED/FAILED',
  `pushed_time` datetime DEFAULT NULL COMMENT '推送时间',
  `receiver_scope` varchar(64) NOT NULL DEFAULT 'ALL' COMMENT '接收范围，外网测试默认ALL',
  `message_id` bigint DEFAULT NULL COMMENT '中心消息编号【需确认】',
  `status` varchar(32) NOT NULL DEFAULT 'OPEN' COMMENT '处理状态：OPEN/CLOSED',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_cost_warning_project` (`tenant_id`, `project_id`),
  KEY `idx_cost_warning_work_order` (`tenant_id`, `work_order_id`),
  KEY `idx_cost_warning_push` (`tenant_id`, `push_status`, `warning_level`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='成本库-预警记录';
