const fs=require('fs'),path=require('path'),crypto=require('crypto')
const {manifest,out,kit,root}=require('./assemble.cjs')
const {essentials}=require('./essentials.cjs')
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')
const files=p=>fs.readdirSync(p,{withFileTypes:true}).flatMap(e=>e.isDirectory()?files(path.join(p,e.name)):[path.join(p,e.name)])
const copy=(a,b)=>{fs.mkdirSync(path.dirname(b),{recursive:true});fs.copyFileSync(a,b)}
for(const name of ['verify-package.ps1','verify-package.sh'])copy(path.join(root,'deploy/cost-server-offline-template/tools',name),path.join(out,'tools',name))
copy(path.join(__dirname,'verify-artifacts.ps1'),path.join(out,'tools/verify-0907-artifacts.ps1'))
for(const name of ['0907验证结果.md','0907内网操作卡.md'])for(const target of [kit,out])copy(path.join(__dirname,name),path.join(target,name))
for(const file of files(__dirname).filter(p=>!p.endsWith('test.cjs')))copy(file,path.join(out,'tools/release-source-0907',path.relative(__dirname,file)))
const info=path.join(out,'RELEASE-INFO.txt')
let text=fs.readFileSync(info,'utf8').replace(/frontendZipSha256=.*/,m=>m.split('=')[0]+'='+m.split('=')[1].toUpperCase())
text=text.replace(/postgresql92Validation=.*/,'postgresql92Validation=see 0907验证结果.md; isolated tests are not intranet acceptance')
if(process.argv.includes('--formal'))text=text.replace('releaseType=candidate','releaseType=formal')
fs.writeFileSync(info,text)
essentials(kit);essentials(out,true)
const sourcePath=path.join(out,'SOURCE-MANIFEST.json'),source=JSON.parse(fs.readFileSync(sourcePath))
source.files=Object.fromEntries(files(out).filter(p=>!p.includes(path.sep+'frontend'+path.sep)&&!p.endsWith('.jar')&&!['SOURCE-MANIFEST.json','SHA256SUMS.txt','RELEASE-INFO.txt'].includes(path.basename(p))).map(p=>[path.relative(out,p).replace(/\\/g,'/'),sha(p)]))
fs.writeFileSync(sourcePath,JSON.stringify(source,null,2))
manifest(kit);manifest(out)
console.log('Refreshed release source snapshot and complete hashes')
